import yaml
prompt_default = yaml.safe_load(open("LLM_PublicHouseAllocation/prompt/prompt/prompt.yaml"))

from LLM_PublicHouseAllocation.registry import Registry
prompt_registry = Registry(name="PromptRegistry")
from LLM_PublicHouseAllocation.prompt.prompt.base_prompt import BasePromptTemplate
from LLM_PublicHouseAllocation.prompt.prompt.choose_house import Choose_HousePromptTemplate
from LLM_PublicHouseAllocation.prompt.prompt.choose_community import Choose_CommunityPromptTemplate
from LLM_PublicHouseAllocation.prompt.prompt.comment import CommentPromptTemplate
from LLM_PublicHouseAllocation.prompt.prompt.forum import Forum_PromptTemplate
from LLM_PublicHouseAllocation.prompt.prompt.correct import Correct_Choose_House_PromptTemplate,Correct_Choose_Community_PromptTemplate